Controllers/RollController.cs
using AdminDemo.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections;
using System.Collections.Generic;

namespace AdminDemo.Controllers
{
    public class RollController : Controller
    {
        private readonly AdminContext _Rc;
        public RollController(AdminContext Rc)
        {
            _Rc = Rc;
        }
        public IActionResult IndexRoll()
        {
            IEnumerable<RollMaster> RollList = _Rc.Tbl_Roll_Master;
            return View(RollList);
        }
        //Get-Create
        public IActionResult CreateRoll()
        {
            return View();
        }

       //Post-Create
       [HttpPost]
       [ValidateAntiForgeryToken]
       public IActionResult CreateRoll(RollMaster obj)
        {
            if (ModelState.IsValid)
            {
                _Rc.Tbl_Roll_Master.Add(obj);
                _Rc.SaveChanges();
                return RedirectToAction("IndexRoll");
            }
            return View(obj);
        }

        //Get-Edit
        public IActionResult EditRoll(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _Rc.Tbl_Roll_Master.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditRoll(RollMaster roll)
        {
            if (ModelState.IsValid)
            {
                _Rc.Tbl_Roll_Master.Update(roll);
                _Rc.SaveChanges();
                return RedirectToAction("IndexRoll");
            }
            return View();
        }

        //GET-Delete
        public IActionResult DeleteRoll(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _Rc.Tbl_Roll_Master.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }


        //Post-Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePostRoll(RollMaster roll)
        {
            var obj = _Rc.Tbl_Roll_Master.Find(roll.RollId);

            if (obj == null)
            {
                return NotFound();

            }
            _Rc.Tbl_Roll_Master.Remove(obj);
            _Rc.SaveChanges();
            return RedirectToAction("IndexRoll");




        }

    }
}

Views/Roll/CreateRoll.cshtml
@model AdminDemo.Models.RollMaster

<form method="post" asp-action="CreateRoll">
    <div class="border p-3">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-info Pl-3">Add Roll</h2>
        </div>

        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="RollName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="RollName" class="form-control" />
                        <span asp-validation-for="RollName" class="text-danger"></span>
                    </div>
                </div>



                <div class="form-group row">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Create" />
                        </div>

                        <div class="col">
                            <a asp-action="IndexRoll" class="btn btn-primary w-100">
                                <i class="fa-solid fa-arrow-right-to-bracket"></i> &nbsp;  Back
                            </a>
                        </div>
                    </div>
                </div>

            </div>
            <div class="col-4">
            </div>
        </div>
    </div>
</form>


@section scripts{
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}

Views/Roll/DeleteRoll.cshtml
@model AdminDemo.Models.RollMaster


<form method-post asp-action="DeletePostRoll">

    <div class="border p-3">
      <input asp-for="RollId" hidden />
        <div class="form-group row">
            <h2 class="text-info pl-3">Delete Roll</h2>
        </div>

    <div class="row">
        <div class="col-8">

             <div class="form-group row">
                <div class="col-4">
                    <label asp-for="RollName"></label>
                </div>
                <div class="col-8">
                   <input asp-for="RollName" disabled class="form-control"/>

                </div>
            </div>

        <div class="form-group row">
            <div class="col-8 offset-4 row">
                <div class="col">
                    <input type="submit" class="btn btn-danger w-100" value="Delete"/> 
                </div>

                <div class="col">
                    <a asp-action="IndexRoll" class="btn btn-primary w-100">
                    <i class="fa fa-arrow-right-to-bracket"></i> Back 
                     </a>
                </div>
            </div>
        </div>
      </div>
        <div class="col-4">

        </div>

 </div>
 </div>

</form>

@section scripts{
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}

Views/Roll/EditRoll.cshtml
@model AdminDemo.Models.RollMaster


<form method-post asp-action="EditRoll" asp-controller="Roll">

    <div class="border p-3">
        <input asp-for="RollId" hidden />
        <div class="form-group row">
            <h2 class="text-info pl-3">Edit Roll</h2>
        </div>

        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="RollName"></label>
                    </div>
                    <div class="col-8">
                         <input asp-for="RollName" class="form-control"/>
                       
                        <span asp-validation-for="RollName" class="text-danger"></span>
                    </div>
                </div>





                <div class="form-group row">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Update" />
                        </div>

                        <div class="col">
                            <a asp-action="IndexRoll" class="btn btn-primary w-100">
                                <i class="fa-solid fa-arrow-right-to-bracket"></i> &nbsp Back
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
            </div>

        </div>
    </div>

</form>

@section scripts{
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}

Views/Roll/IndexRoll.cshtml
@model IEnumerable<AdminDemo.Models.RollMaster>


<div class="container p-3">
    <div class="row pt-4">

        <div class="col-6 text-left">
            <a asp-controller="Roll" asp-action="CreateRoll" class="btn btn-primary">
                <i class="fa fa-plus"></i> &nbsp; Create New Roll
            </a>
        </div>
    </div>
</div>



@if (Model.Count() > 0)
{
    <div>
        <table id="parentdiv" class="display nowrap" style="width:100%">
            <thead>
                <tr>
                    <th>
                        RollName
                    </th>

                    <th>

                    </th>
            <tbody>
                        @foreach (var obj in Model)
                        {
                    <tr>

                        <td width:"50%">@obj.RollName</td>


                        <td class="text-center">
                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="Roll" asp-route-Id="@obj.RollId" asp-action="EditRoll" class="btn btn-primary btn-sm">
                                    <i class="fa fa-pen-to-square"></i> &nbsp;
                                </a>
                                <a asp-controller="Roll" asp-route-Id="@obj.RollId" asp-action="DeleteRoll" class="btn btn-danger btn-sm">
                                    <i class="fa fa-trash-can"></i> &nbsp;
                                </a>
                            </div>
                        </td>
                    </tr>
                        }
            </tbody>
        </table>
    </div>


}

 else
    {
        <p>No Roll data</p>
    }